name:                semantic-code-editor
version:             0.1.0.0
github:              "fboeller/semantic-code-editor"
license:             BSD3
author:              "Fabian Böller"
maintainer:          "fabianboeller@googlemail.com"
copyright:           "2019 Fabian Böller"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/fboeller/semantic-code-editor#readme>

dependencies:
- base >= 4.7 && < 5
- language-java >= 0.2.9
- parsec >= 3.1.13.0
- microlens
- microlens-th
- lens
- vty
- ansi-terminal
- filepath
- directory
- directory-tree
- unix
- containers
- haskeline
- transformers

library:
  source-dirs: src

executables:
  sce:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - semantic-code-editor

tests:
  sce-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - semantic-code-editor
